version: "3.7"

services:
  account:
    build:
      context: .
      dockerfile: ./account/dockerfiles/app.dockerfile
    depends_on:
      - account_db
    environment:
      DATABASE_URL: postgres://shopvee:123456@account_db/shopvee?sslmode=disable
    restart: on-failure

  account_db:
    build:
      context: ./account
      dockerfile: ./dockerfiles/db.dockerfile
    environment:
      POSTGRES_DB: shopvee
      POSTGRES_USER: shopvee
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  graphql:
    build:
      context: .
      dockerfile: ./graph/dockerfiles/app.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - account
    environment:
      ACCOUNT_SERVICE_URL: account:8080
      PORT: 8080
    restart: on-failure
