version: "3.7"

services:
  account:
    build:
      context: .
      dockerfile: ./account/dockerfiles/app.dockerfile
    depends_on:
      - account_db
    environment:
      DATABASE_URL: postgres://shopvee:123456@account_db/shopvee?sslmode=disable
    restart: on-failure
  
  account_db:
    build:
      context: ./account
      dockerfile: ./dockerfiles/db.dockerfile
    environment:
      POSTGRES_DB: shopvee
      POSTGRES_USER: shopvee
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  product:
    build:
      context: .
      dockerfile: ./product/dockerfiles/app.dockerfile
    depends_on:
      - product_db
    environment:
      DATABASE_URL: postgres://shopvee:123456@product_db/shopvee?sslmode=disable
    restart: on-failure

  product_db:
    build:
      context: ./product
      dockerfile: ./dockerfiles/db.dockerfile
    environment:
      POSTGRES_DB: shopvee
      POSTGRES_USER: shopvee
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
  
  order:
    build:
      context: .
      dockerfile: ./order/dockerfiles/app.dockerfile
    depends_on:
      - order_db
    environment:
      DATABASE_URL: postgres://shopvee:123456@order_db/shopvee?sslmode=disable
      ACCOUNT_SERVICE_URL: account:8080
      PRODUCT_SERVICE_URL: product:8080
    restart: on-failure

  order_db:
    build:
      context: ./order
      dockerfile: ./dockerfiles/db.dockerfile
    environment:
      POSTGRES_DB: shopvee
      POSTGRES_USER: shopvee
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped

  graphql:
    build:
      context: .
      dockerfile: ./graphql/dockerfiles/app.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - account
    environment:
      ACCOUNT_SERVICE_URL: account:8080
      PRODUCT_SERVICE_URL: product:8080
      ORDER_SERVICE_URL: order:8080
      PORT: 8080
    restart: on-failure
